Use Hash#dig for fetching pagination metadata
This helps protect against being nil. Unfortunately I could not
accurately reproduce this issue:

  NoMethodError: undefined method `[]' for nil:NilClass
  zaikio-client-helpers (0.2.1) lib/zaikio/client/helpers/pagination.rb:66 block (2 levels) in <class:Relation>
  zaikio-client-helpers (0.2.1) lib/zaikio/client/helpers/pagination.rb:83 supports_pagination?
  zaikio-client-helpers (0.2.1) lib/zaikio/client/helpers/pagination.rb:98 each
  ...

It isn't easy to tell whether `metadata` is `nil`, or
`metadata[PAGINATION_KEY]` is `nil`. The Spyke code indicates that
`metadata` is either `response[:metadata] || {}` so I presume that
`metadata[PAGINATION_KEY]` is our culprit here, but I can't work out
under what circumstances it would be so.

Anyway - if we didn't parse the pagination headers correctly, the
response won't support pages, so we can safely return nil.